# Pull the official base image  
FROM node:alpine3.13 as build
 
# Set your working directory  
WORKDIR /app  
 
# Add `/app/node_modules/.bin` to $PATH  
ENV PATH /app/node_modules/.bin:$PATH  
 
# Install application dependencies
COPY package*.json ./
RUN npm install --silent
 
# Add app  
COPY . ./  
 
# Will build app  
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
